version: '3.7'
services:
  node12:
    build:
      args:
        NODE_VERSION: 12
    image: ${IMAGE:-nodejs}:12

  node14:
    build:
      args:
        NODE_VERSION: 14
    image: ${IMAGE:-nodejs}:14

  node16:
    build:
      args:
        NODE_VERSION: 16
    image: ${IMAGE:-nodejs}:16
