version: '3.7'
services:
  node12:
    build:
      context: .
      args:
        NODE_VERSION: 12
    image: nodejs:12

  node14:
    build:
      context: .
      args:
        NODE_VERSION: 14
    image: nodejs:14

  node16:
    build:
      context: .
      args:
        NODE_VERSION: 16
    image: nodejs:16
