name: Docker build and push
on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "0 2 * * 0"

env:
  IMAGE_NAME: nodejs
  DOCKER_BUILDKIT: 1

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    strategy:
      matrix:
        node: [12, 14, 16]

    steps:
      - uses: actions/checkout@v2

      - uses: hadolint/hadolint-action@v1.5.0
        with:
          dockerfile: Dockerfile
          config: hadolint-ci.yaml

      - name: Build image
        run: docker-compose -f docker-compose.yml build node${{ matrix.node }}
        if: github.event_name != 'pull_request'

      - name: Log into registry
        # This is where you will update the PAT to GITHUB_TOKEN
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        if: github.event_name != 'pull_request'

      - name: Push image
        run: docker-compose -f docker-compose.yml push node${{ matrix.node }}
        if: github.event_name != 'pull_request'

      - name: Tag build-versioned image
        run: docker tag ghcr.io/shoraiconsulting/nodejs:${{ matrix.node }} ghcr.io/shoraiconsulting/nodejs:${{ matrix.node }}-${{ github.run_number }}
        if: github.event_name != 'pull_request'

      - name: Push versioned image
        run: docker push ghcr.io/shoraiconsulting/nodejs:${{ matrix.node }}-${{ github.run_number }}
        if: github.event_name != 'pull_request'

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        if: ${{ success() && (github.event_name != 'pull_request') }}
        env:
          SLACK_WEBHOOK: ${{ secrets.BUILD_NOTIFY_SLACK }}
          SLACK_COLOR: green
          SLACK_MESSAGE: 'Good luck, this time... :rocket:'
          SLACK_TITLE: Build successful

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        if: ${{ failure() && (github.event_name != 'pull_request') }}
        env:
          SLACK_WEBHOOK: ${{ secrets.BUILD_NOTIFY_SLACK }}
          SLACK_COLOR: red
          SLACK_MESSAGE: 'Seems whatever you did failed :unrocket:'
          SLACK_TITLE: Build failed
